-- ============================================
-- Career Roadmap Schema
-- Generated by RoadmapAgent
-- ============================================

-- Drop existing tables to ensure clean install
DROP TABLE IF EXISTS roadmap_phase_progress CASCADE;
DROP TABLE IF EXISTS career_roadmap CASCADE;

-- Main career_roadmap table
CREATE TABLE career_roadmap (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    domain VARCHAR(20) NOT NULL CHECK (domain IN ('tech', 'medical')),
    roadmap_json JSONB NOT NULL,
    roadmap_version VARCHAR(10) NOT NULL DEFAULT 'v1',
    confidence_level VARCHAR(10) CHECK (confidence_level IN ('low', 'medium', 'high')),
    overall_duration_estimate VARCHAR(100),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT unique_active_roadmap_per_user UNIQUE (user_id, is_active) 
        DEFERRABLE INITIALLY DEFERRED
);

-- Phase progress tracking table
CREATE TABLE roadmap_phase_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    roadmap_id UUID NOT NULL REFERENCES career_roadmap(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    phase_number INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'locked' 
        CHECK (status IN ('locked', 'active', 'completed', 'skipped')),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    progress_percentage INTEGER DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT unique_phase_per_roadmap UNIQUE (roadmap_id, phase_number)
);

-- ============================================
-- Indexes for Performance
-- ============================================

CREATE INDEX IF NOT EXISTS idx_career_roadmap_user_id 
    ON career_roadmap(user_id);

CREATE INDEX IF NOT EXISTS idx_career_roadmap_domain 
    ON career_roadmap(domain);

CREATE INDEX IF NOT EXISTS idx_career_roadmap_active 
    ON career_roadmap(user_id, is_active) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_career_roadmap_json_phases 
    ON career_roadmap USING GIN (roadmap_json jsonb_path_ops);

CREATE INDEX IF NOT EXISTS idx_roadmap_phase_progress_roadmap 
    ON roadmap_phase_progress(roadmap_id);

CREATE INDEX IF NOT EXISTS idx_roadmap_phase_progress_user 
    ON roadmap_phase_progress(user_id, status);

-- ============================================
-- Row Level Security (RLS)
-- ============================================

ALTER TABLE career_roadmap ENABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_phase_progress ENABLE ROW LEVEL SECURITY;

-- Users can only see their own roadmaps
CREATE POLICY "Users can view own roadmaps" ON career_roadmap
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Service role can manage roadmaps" ON career_roadmap
    FOR ALL USING (auth.role() = 'service_role');

-- Users can only see their own phase progress
CREATE POLICY "Users can view own phase progress" ON roadmap_phase_progress
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Service role can manage phase progress" ON roadmap_phase_progress
    FOR ALL USING (auth.role() = 'service_role');

-- ============================================
-- Functions
-- ============================================

-- Function to upsert a roadmap (deactivate old, insert new)
CREATE OR REPLACE FUNCTION upsert_career_roadmap(
    p_user_id UUID,
    p_domain VARCHAR(20),
    p_roadmap_json JSONB,
    p_roadmap_version VARCHAR(10) DEFAULT 'v1',
    p_confidence_level VARCHAR(10) DEFAULT 'medium',
    p_duration_estimate VARCHAR(100) DEFAULT NULL
) RETURNS UUID AS $$
DECLARE
    v_roadmap_id UUID;
BEGIN
    -- Deactivate existing active roadmap
    UPDATE career_roadmap 
    SET is_active = false, updated_at = NOW()
    WHERE user_id = p_user_id AND is_active = true;
    
    -- Insert new roadmap
    INSERT INTO career_roadmap (
        user_id, domain, roadmap_json, roadmap_version, 
        confidence_level, overall_duration_estimate, is_active
    ) VALUES (
        p_user_id, p_domain, p_roadmap_json, p_roadmap_version,
        p_confidence_level, p_duration_estimate, true
    ) RETURNING id INTO v_roadmap_id;
    
    RETURN v_roadmap_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to initialize phase progress for a roadmap
CREATE OR REPLACE FUNCTION initialize_roadmap_phases(
    p_roadmap_id UUID,
    p_user_id UUID,
    p_total_phases INTEGER
) RETURNS VOID AS $$
DECLARE
    i INTEGER;
BEGIN
    -- Delete existing phase progress
    DELETE FROM roadmap_phase_progress WHERE roadmap_id = p_roadmap_id;
    
    -- Create phase progress entries
    FOR i IN 1..p_total_phases LOOP
        INSERT INTO roadmap_phase_progress (
            roadmap_id, user_id, phase_number, status
        ) VALUES (
            p_roadmap_id, 
            p_user_id, 
            i, 
            CASE WHEN i = 1 THEN 'active' ELSE 'locked' END
        );
    END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to advance to next phase
CREATE OR REPLACE FUNCTION advance_roadmap_phase(
    p_roadmap_id UUID,
    p_user_id UUID,
    p_current_phase INTEGER
) RETURNS BOOLEAN AS $$
DECLARE
    v_next_phase INTEGER;
BEGIN
    -- Mark current phase as completed
    UPDATE roadmap_phase_progress
    SET status = 'completed', 
        completed_at = NOW(), 
        progress_percentage = 100,
        updated_at = NOW()
    WHERE roadmap_id = p_roadmap_id 
      AND phase_number = p_current_phase
      AND user_id = p_user_id;
    
    -- Find and unlock next phase
    v_next_phase := p_current_phase + 1;
    
    UPDATE roadmap_phase_progress
    SET status = 'active', 
        started_at = NOW(),
        updated_at = NOW()
    WHERE roadmap_id = p_roadmap_id 
      AND phase_number = v_next_phase
      AND user_id = p_user_id;
    
    RETURN FOUND;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get current active phase
CREATE OR REPLACE FUNCTION get_current_phase(
    p_user_id UUID
) RETURNS TABLE (
    roadmap_id UUID,
    phase_number INTEGER,
    phase_title TEXT,
    status VARCHAR(20),
    progress_percentage INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        rpp.roadmap_id,
        rpp.phase_number,
        (cr.roadmap_json->'phases'->>(rpp.phase_number - 1)->>'phase_title')::TEXT,
        rpp.status,
        rpp.progress_percentage
    FROM roadmap_phase_progress rpp
    JOIN career_roadmap cr ON cr.id = rpp.roadmap_id
    WHERE rpp.user_id = p_user_id 
      AND cr.is_active = true
      AND rpp.status = 'active'
    LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- Views
-- ============================================

-- View for roadmap with phase progress
CREATE OR REPLACE VIEW v_roadmap_with_progress AS
SELECT 
    cr.id as roadmap_id,
    cr.user_id,
    cr.domain,
    cr.roadmap_version,
    cr.confidence_level,
    cr.overall_duration_estimate,
    cr.roadmap_json,
    cr.is_active,
    cr.created_at,
    jsonb_agg(
        jsonb_build_object(
            'phase_number', rpp.phase_number,
            'status', rpp.status,
            'progress_percentage', rpp.progress_percentage,
            'started_at', rpp.started_at,
            'completed_at', rpp.completed_at
        ) ORDER BY rpp.phase_number
    ) as phase_progress
FROM career_roadmap cr
LEFT JOIN roadmap_phase_progress rpp ON rpp.roadmap_id = cr.id
WHERE cr.is_active = true
GROUP BY cr.id;

-- View for roadmap summary
CREATE OR REPLACE VIEW v_roadmap_summary AS
SELECT 
    cr.user_id,
    cr.domain,
    cr.confidence_level,
    cr.overall_duration_estimate,
    jsonb_array_length(cr.roadmap_json->'phases') as total_phases,
    COUNT(CASE WHEN rpp.status = 'completed' THEN 1 END) as completed_phases,
    COUNT(CASE WHEN rpp.status = 'active' THEN 1 END) as active_phases,
    MAX(CASE WHEN rpp.status = 'active' THEN rpp.phase_number END) as current_phase_number,
    cr.created_at
FROM career_roadmap cr
LEFT JOIN roadmap_phase_progress rpp ON rpp.roadmap_id = cr.id
WHERE cr.is_active = true
GROUP BY cr.id;

-- ============================================
-- Triggers
-- ============================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_roadmap_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_career_roadmap_updated
    BEFORE UPDATE ON career_roadmap
    FOR EACH ROW
    EXECUTE FUNCTION update_roadmap_timestamp();

CREATE TRIGGER trigger_phase_progress_updated
    BEFORE UPDATE ON roadmap_phase_progress
    FOR EACH ROW
    EXECUTE FUNCTION update_roadmap_timestamp();

-- ============================================
-- Comments
-- ============================================

COMMENT ON TABLE career_roadmap IS 'Stores AI-generated career roadmaps with phased learning plans';
COMMENT ON TABLE roadmap_phase_progress IS 'Tracks user progress through roadmap phases';
COMMENT ON COLUMN career_roadmap.roadmap_json IS 'JSONB containing phases array with focus_areas, skills, outcomes, criteria';
COMMENT ON COLUMN career_roadmap.is_active IS 'Only one active roadmap per user - old ones are archived';
